# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: pbft.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'pbft.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\npbft.proto\"-\n\x07Message\x12\x0e\n\x06sender\x18\x01 \x01(\t\x12\x12\n\nblock_hash\x18\x02 \x01(\t\"\x1b\n\x08Response\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32o\n\x0bPBFTService\x12!\n\nPrePrepare\x12\x08.Message\x1a\t.Response\x12\x1e\n\x07Prepare\x12\x08.Message\x1a\t.Response\x12\x1d\n\x06\x43ommit\x12\x08.Message\x1a\t.Responseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'pbft_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MESSAGE']._serialized_start=14
  _globals['_MESSAGE']._serialized_end=59
  _globals['_RESPONSE']._serialized_start=61
  _globals['_RESPONSE']._serialized_end=88
  _globals['_PBFTSERVICE']._serialized_start=90
  _globals['_PBFTSERVICE']._serialized_end=201
# @@protoc_insertion_point(module_scope)
