# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import pbft_pb2 as pbft__pb2


class PBFTServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PrePrepare = channel.unary_unary(
                '/PBFTService/PrePrepare',
                request_serializer=pbft__pb2.Message.SerializeToString,
                response_deserializer=pbft__pb2.Response.FromString,
                )
        self.Prepare = channel.unary_unary(
                '/PBFTService/Prepare',
                request_serializer=pbft__pb2.Message.SerializeToString,
                response_deserializer=pbft__pb2.Response.FromString,
                )
        self.Commit = channel.unary_unary(
                '/PBFTService/Commit',
                request_serializer=pbft__pb2.Message.SerializeToString,
                response_deserializer=pbft__pb2.Response.FromString,
                )


class PBFTServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def PrePrepare(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Prepare(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Commit(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PBFTServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PrePrepare': grpc.unary_unary_rpc_method_handler(
                    servicer.PrePrepare,
                    request_deserializer=pbft__pb2.Message.FromString,
                    response_serializer=pbft__pb2.Response.SerializeToString,
            ),
            'Prepare': grpc.unary_unary_rpc_method_handler(
                    servicer.Prepare,
                    request_deserializer=pbft__pb2.Message.FromString,
                    response_serializer=pbft__pb2.Response.SerializeToString,
            ),
            'Commit': grpc.unary_unary_rpc_method_handler(
                    servicer.Commit,
                    request_deserializer=pbft__pb2.Message.FromString,
                    response_serializer=pbft__pb2.Response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'PBFTService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class PBFTService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def PrePrepare(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/PBFTService/PrePrepare',
            pbft__pb2.Message.SerializeToString,
            pbft__pb2.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Prepare(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/PBFTService/Prepare',
            pbft__pb2.Message.SerializeToString,
            pbft__pb2.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Commit(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/PBFTService/Commit',
            pbft__pb2.Message.SerializeToString,
            pbft__pb2.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
