# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pbft.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\npbft.proto\"-\n\x07Message\x12\x0e\n\x06sender\x18\x01 \x01(\t\x12\x12\n\nblock_hash\x18\x02 \x01(\t\"\x1b\n\x08Response\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32o\n\x0bPBFTService\x12!\n\nPrePrepare\x12\x08.Message\x1a\t.Response\x12\x1e\n\x07Prepare\x12\x08.Message\x1a\t.Response\x12\x1d\n\x06\x43ommit\x12\x08.Message\x1a\t.Responseb\x06proto3')



_MESSAGE = DESCRIPTOR.message_types_by_name['Message']
_RESPONSE = DESCRIPTOR.message_types_by_name['Response']
Message = _reflection.GeneratedProtocolMessageType('Message', (_message.Message,), {
  'DESCRIPTOR' : _MESSAGE,
  '__module__' : 'pbft_pb2'
  # @@protoc_insertion_point(class_scope:Message)
  })
_sym_db.RegisterMessage(Message)

Response = _reflection.GeneratedProtocolMessageType('Response', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSE,
  '__module__' : 'pbft_pb2'
  # @@protoc_insertion_point(class_scope:Response)
  })
_sym_db.RegisterMessage(Response)

_PBFTSERVICE = DESCRIPTOR.services_by_name['PBFTService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MESSAGE._serialized_start=14
  _MESSAGE._serialized_end=59
  _RESPONSE._serialized_start=61
  _RESPONSE._serialized_end=88
  _PBFTSERVICE._serialized_start=90
  _PBFTSERVICE._serialized_end=201
# @@protoc_insertion_point(module_scope)
