# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: raft.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'raft.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nraft.proto\"`\n\x0bVoteRequest\x12\x0c\n\x04term\x18\x01 \x01(\x04\x12\x14\n\x0c\x63\x61ndidate_id\x18\x02 \x01(\t\x12\x16\n\x0elast_log_index\x18\x03 \x01(\x04\x12\x15\n\rlast_log_term\x18\x04 \x01(\x04\"2\n\x0cVoteResponse\x12\x0c\n\x04term\x18\x01 \x01(\x04\x12\x14\n\x0cvote_granted\x18\x02 \x01(\x08\"\x91\x01\n\x0c\x45ntryRequest\x12\x0c\n\x04term\x18\x01 \x01(\x04\x12\x11\n\tleader_id\x18\x02 \x01(\t\x12\x16\n\x0eprev_log_index\x18\x03 \x01(\x04\x12\x15\n\rprev_log_term\x18\x04 \x01(\x04\x12\x1a\n\x07\x65ntries\x18\x05 \x03(\x0b\x32\t.LogEntry\x12\x15\n\rleader_commit\x18\x06 \x01(\x04\".\n\rEntryResponse\x12\x0c\n\x04term\x18\x01 \x01(\x04\x12\x0f\n\x07success\x18\x02 \x01(\x08\")\n\x08LogEntry\x12\x0c\n\x04term\x18\x01 \x01(\x04\x12\x0f\n\x07\x63ommand\x18\x02 \x01(\t\"5\n\x11\x43onnectionRequest\x12\x0c\n\x04peer\x18\x01 \x01(\t\x12\x12\n\ndisconnect\x18\x02 \x01(\x08\"%\n\x12\x43onnectionResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"\x19\n\nGetRequest\x12\x0b\n\x03key\x18\x01 \x01(\t\"\x1c\n\x0bGetResponse\x12\r\n\x05value\x18\x01 \x01(\t2\xcb\x01\n\x08RaftNode\x12*\n\x0bRequestVote\x12\x0c.VoteRequest\x1a\r.VoteResponse\x12.\n\rAppendEntries\x12\r.EntryRequest\x1a\x0e.EntryResponse\x12<\n\x11\x43ontrolConnection\x12\x12.ConnectionRequest\x1a\x13.ConnectionResponse\x12%\n\x08GetValue\x12\x0b.GetRequest\x1a\x0c.GetResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'raft_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_VOTEREQUEST']._serialized_start=14
  _globals['_VOTEREQUEST']._serialized_end=110
  _globals['_VOTERESPONSE']._serialized_start=112
  _globals['_VOTERESPONSE']._serialized_end=162
  _globals['_ENTRYREQUEST']._serialized_start=165
  _globals['_ENTRYREQUEST']._serialized_end=310
  _globals['_ENTRYRESPONSE']._serialized_start=312
  _globals['_ENTRYRESPONSE']._serialized_end=358
  _globals['_LOGENTRY']._serialized_start=360
  _globals['_LOGENTRY']._serialized_end=401
  _globals['_CONNECTIONREQUEST']._serialized_start=403
  _globals['_CONNECTIONREQUEST']._serialized_end=456
  _globals['_CONNECTIONRESPONSE']._serialized_start=458
  _globals['_CONNECTIONRESPONSE']._serialized_end=495
  _globals['_GETREQUEST']._serialized_start=497
  _globals['_GETREQUEST']._serialized_end=522
  _globals['_GETRESPONSE']._serialized_start=524
  _globals['_GETRESPONSE']._serialized_end=552
  _globals['_RAFTNODE']._serialized_start=555
  _globals['_RAFTNODE']._serialized_end=758
# @@protoc_insertion_point(module_scope)
